messa/pyladies-courseware

- backend/cw_backend/model/task_solutions.py
- backend/cw_backend/views/tasks.py
- frontend/components/TaskReviewLessonSummary.js
>  moznost videt, ze se neco noveho stale nekde, kde jsem komentoval/hodnotil/...
>  * např. v tabulce mít kromě kolečka/fajfky i další symbol pro "čeká na reakci kouče" (#13, #16) 
>  * aby byl viděl stav: "čeká na kouče", "čeká na účastnici", nebo "všichni jsou spokojení"
>  * ale ještě víc zvýraznit ty případy, kde jsem předtím něco psal já
> Simple solution state highlight

- backend/cw_backend/views/__init__.py
- backend/cw_backend/views/users.py
- frontend/pages/course.js
Issue:
- Vyřešit zapisování studentů do kurzů #46
Popis:
- u aktivních kurzů se zobrazí tlačítko 'Jste součástí kurzu'(neaktivní) : 'Přihlásit se do kurzu'(aktivní)
- kliknutí -> POST na API -> když vše dopadne dobře reload stránky
UI by se dalo vymyslet lépe, ale zatím jsem nevymyslel jak
>  Enrollment students to courses 

- data/2019_pyladies_plzen_spring/course.yaml
- data/2019_pyladies_plzen_spring/tasks/03_cykly.yaml
- data/2019_pyladies_plzen_spring/tasks/03_cykly_konzole.yaml
- data/2019_pyladies_plzen_spring/tasks/03_cykly_zelva.yaml
- data/2019_pyladies_plzen_spring/tasks/04_procvicovani_for.yaml
> changes in third lesson of Pilsen course

- data/2019_pyladies_praha_spring/tasks/01_first_steps.yaml
Sedmička sama o sobě nebyla zadána jako úkol.
> Sloučení úkolu 7 a 8

- data/2019_pyladies_praha_spring/tasks/08_slovniky.yaml
Copied update made by @frenzymadness in Ostrava :)
https://github.com/PyLadiesCZ/naucse.python.cz/pull/29/commits/c796e475824d0a13fb07d6a061259d4f9add4e3e
> add examples to 08_slovniky.yaml

- data/2019_pyladies_praha_spring/course_ntk.yaml
- data/2019_pyladies_praha_spring/tasks/11_tridy2.yaml
Vykradeno z https://github.com/messa/pyladies-materials/tree/master/201805_tridy_vozovy_park
> Homework for lesson Classes & Inheritance added

- data/2019_pyladies_brno_spring/course_monday.yaml
- data/2019_pyladies_brno_spring/tasks/12_files.yaml
Hope this works, didn't check.
(`mongodb` switched to a non-open-source licence and got removed from my distro. Compiling it takes hours.)
> Brno: Add tasks for files & paths

- frontend/components/TaskReviewLessonSummary.js
- frontend/components/lesson/TaskReview.js
- frontend/pages/session.js
Issue #86 
Dané sloupečky se nezobrazí, v review informace Odevzdané řešení/Úloha se neodevzdává
> Do not show unsubmittable tasks in the summary table

- backend/cw_backend/model/task_solutions.py
- frontend/components/TaskSubmission.js
- frontend/components/lesson/TaskSolution.js
**Pohled kouče**
**Pohled účastníka**
> Solution versions in task solution view

- backend/cw_backend/model/users.py
- backend/cw_backend/views/admin_users.py
- frontend/components/admin/UserDetail.js
> Simple user administration

- backend/cw_backend/model/task_solutions.py
- backend/cw_backend/views/tasks.py
- frontend/components/TaskSolutionForm.js
- frontend/components/TaskSubmission.js
- frontend/components/TaskSubmissionLessonSummary.js
- frontend/pages/session.js
add button like "Cancel" to do not save solution #126 
Setkání 2019-06-26 (Student lesson summary) #128
> Student lesson summary and cancel button for solution form

- backend/cw_backend/model/task_solutions.py
- backend/cw_backend/views/tasks.py
- frontend/components/TaskReviewLessonSummary.js
- frontend/components/lesson/HomeworkTask.js
- frontend/components/lesson/TaskReview.js
- frontend/pages/session.js
- frontend/pages/task.js
> Add a task detail page with all solutions

- data/2019_pyladies_plzen_autumn/course.yaml
- data/2019_pyladies_plzen_autumn/tasks/01_first_steps.yaml
- data/2019_pyladies_plzen_autumn/tasks/02_chybove_hlasky.yaml
- data/2019_pyladies_plzen_autumn/tasks/02_nebo_anebo_a.yaml
- data/2019_pyladies_plzen_autumn/tasks/02_porovnavani.yaml
- data/2019_pyladies_plzen_autumn/tasks/02_promenne.yaml
- data/2019_pyladies_plzen_autumn/tasks/02_prvni_program.yaml
- data/2019_pyladies_plzen_autumn/tasks/03_cykly.yaml
- data/2019_pyladies_plzen_autumn/tasks/03_cykly_konzole.yaml
- data/2019_pyladies_plzen_autumn/tasks/03_cykly_zelva.yaml
- data/2019_pyladies_plzen_autumn/tasks/04_procvicovani_for.yaml
- data/2019_pyladies_plzen_autumn/tasks/04_vlastni_funkce.yaml
- data/2019_pyladies_plzen_autumn/tasks/05_1d_piskvorky.yaml
- data/2019_pyladies_plzen_autumn/tasks/05_retezce.yaml
- data/2019_pyladies_plzen_autumn/tasks/06_procvicovani_orisky.yaml
- data/2019_pyladies_plzen_autumn/tasks/06_procvicovani_print.yaml
- data/2019_pyladies_plzen_autumn/tasks/07_seznamy.yaml
- data/2019_pyladies_plzen_autumn/tasks/08_slovniky.yaml
- data/2019_pyladies_plzen_autumn/tasks/08_snake.yaml
- data/2019_pyladies_plzen_autumn/tasks/09_1d_piskvorky_testy.yaml
- data/2019_pyladies_plzen_autumn/tasks/09_hangman.yaml
- data/2019_pyladies_plzen_autumn/tasks/10_tridy.yaml
- data/courses.yaml
Hi, this is to add tasks for Pilsen autumn course. The structure is the same as in spring, with the only difference that all aur taks files are now in 2019_pyladies_plzen_autumn, instead of being linked from 2019_pyladies_praha_spring folder. We revised some tasks, which caused confusion.
> Pilsen autumn 2019

- frontend/pages/session.js
> Show help for non-enrolled/non-logged-in users how to submit tasks

- frontend/components/TaskSubmission.js
- frontend/components/lesson/TaskSolution.js
> Add copy to clipboard button to task solution component

- frontend/components/TaskSubmission.js
- frontend/components/lesson/TaskComments.js
- frontend/components/lesson/TaskReview.js
> Added information to which version is comment related to

- frontend/pages/index.js
> Added my courses section to index page

- data/2019_pyladies_brno_autumn/tasks/05_testing.yaml
- frontend/static/tasks/handout_files/2019-autumn/test_piskvorky.py
This includes a new version of the tests – but the file for the previous course shouldn't be modified.
> Adjust connect-three tasks for Brno, Monday

- data/2020_pyladies_olomouc_spring/course.yaml
- data/2020_pyladies_olomouc_spring/tasks/10_pyglet.yaml
- data/2020_pyladies_olomouc_spring/tasks/11_class.yaml
- data/2020_pyladies_olomouc_spring/tasks/12_inheritance.yaml
- data/2020_pyladies_olomouc_spring/tasks/2_first_app.yaml
- data/2020_pyladies_olomouc_spring/tasks/3_loops.yaml
- data/2020_pyladies_olomouc_spring/tasks/4_while.yaml
- data/2020_pyladies_olomouc_spring/tasks/5_def.yaml
- data/2020_pyladies_olomouc_spring/tasks/6_exceptions.yaml
- data/2020_pyladies_olomouc_spring/tasks/7_list.yaml
- data/2020_pyladies_olomouc_spring/tasks/8_dict.yaml
- data/2020_pyladies_olomouc_spring/tasks/9_testing.yaml
- data/courses.yaml
Adds (initial version of) tasks for Olomouc 2020 spring run.
@fivaldi
> Add Olomouc 2020 spring run

- data/2020_pyladies_praha_spring/tasks/03_cyklus_for_zelva.yaml
> úkoly pro třetí lekci

- data/2020_pyladies_praha_spring/course_olsanka.yaml
- data/courses.yaml
- frontend/pages/course.js
@messa hodilo by se to mít v úterý příští týden (3. 2.) nasazené  
cc: @veronikks
> add Prague Olsanka course spring 2020

- data/2020_pyladies_brno_spring/course_monday.yaml
- data/2020_pyladies_brno_spring/tasks/06_list.yaml
- data/2020_pyladies_brno_spring/tasks/08_dict.yaml
- data/2020_pyladies_brno_spring/tasks/12_files.yaml
* Snake: Make coordinates (row, column) rather than sometimes (x, y)
* Rearrange homework for today's lesson, add new "game"
> Brno: Update for today's lesson

- data/2020_pyladies_praha_autumn/course.yaml
- data/2020_pyladies_praha_autumn/tasks/01_prvni_program.yaml
- data/2020_pyladies_praha_autumn/tasks/02_promenne_podminky.yaml
- data/2020_pyladies_praha_autumn/tasks/03_cyklus_for_zelva.yaml
- data/2020_pyladies_praha_autumn/tasks/04_cyklus_while.yaml
- data/2020_pyladies_praha_autumn/tasks/05_vlastni_funkce.yaml
- data/2020_pyladies_praha_autumn/tasks/06_retezce.yaml
- data/2020_pyladies_praha_autumn/tasks/07_opakovani_soubory.yaml
- data/2020_pyladies_praha_autumn/tasks/08_seznamy.yaml
- data/2020_pyladies_praha_autumn/tasks/09_slovniky.yaml
- data/2020_pyladies_praha_autumn/tasks/10_vyjimky_moduly.yaml
- data/2020_pyladies_praha_autumn/tasks/11_clovek.yaml
- data/2020_pyladies_praha_autumn/tasks/12_vozovy_park_v2.yaml
- data/courses.yaml
Přidávám podzimní kurz pro Prahu
cc: @Zuzanita
> add Prague autumn 2020 course

- frontend/pages/task.js
Do not load all task solutions in course when we need just list of students
> Speedup loading of task page

- data/2020_pyladies_praha_autumn/tasks/06_retezce.yaml
Male opravy ve formulaci zadání na lekci s řetězci. Nepovedlo se mi to rozchodit lokálně, tak prosím zkouknout, zda jsem nerozbila.
Prosím o label hacktoberfest-accepted :pray: 
(Opravy nemění zadání, je možno jim to tam naprat i teď za běhu kurzu.)
> male opravy (funkce dostane -> dostane jako argument)

- data/2020_pydata_praha_autumn/course.yaml
- data/2020_pydata_praha_autumn/tasks/ml_1.yaml
Prosím o merge až PO úterní Pydata hodině (tzn. po 27.10. 20:00) :)
> Prague: Add Pydata prg ML1 tasks

- data/2020_pyladies_praha_autumn/tasks/07_opakovani_soubory.yaml
- data/2020_pyladies_praha_autumn/tasks/08_seznamy.yaml
- data/2020_pyladies_praha_autumn/tasks/09_slovniky.yaml
Pár upřesnění v domácích úkolech na základní kurz.
hacktoberfest_accepted :pray:
> drobne upravy a upresneni zadani

- backend/cw_backend/views/auth.py
- frontend/components/Footer.js
- frontend/components/forms/RegistrationForm.js
- frontend/pages/privacy.js
Je tohle OK? V Reactu se moc nevyznám.
> Add a privacy policy

- backend/cw_backend/views/auth.py
- frontend/components/forms/RegistrationForm.js
Apparently, in #267 I forgot to change a bunch of Javascript, so now registration with mail+password is impossible. This should fix it.
It worked on my machine, probably because I didn't restart the backend.
> Fix: Pass data about privacy policy consent to the backend

- data/2021_pyladies_praha_spring/course.yaml
- data/2021_pyladies_praha_spring/tasks/01_prvni_program.yaml
- data/2021_pyladies_praha_spring/tasks/02_promenne_podminky.yaml
- data/2021_pyladies_praha_spring/tasks/03_cyklus_for_zelva.yaml
- data/2021_pyladies_praha_spring/tasks/04_cyklus_while.yaml
- data/2021_pyladies_praha_spring/tasks/05_vlastni_funkce.yaml
- data/2021_pyladies_praha_spring/tasks/06_retezce.yaml
- data/2021_pyladies_praha_spring/tasks/07_opakovani_soubory.yaml
- data/2021_pyladies_praha_spring/tasks/08_seznamy.yaml
- data/2021_pyladies_praha_spring/tasks/09_slovniky.yaml
- data/2021_pyladies_praha_spring/tasks/10_vyjimky_moduly.yaml
- data/2021_pyladies_praha_spring/tasks/11_clovek.yaml
- data/2021_pyladies_praha_spring/tasks/12_vozovy_park_v2.yaml
- data/courses.yaml
Pokud na to hodíte očko budu rád. Případně si to projdu zítra a kdyžtak to mergnu.
> Add pyladies Prague spring 2021 course

- data/2021_online_spring/tasks/08_dict.yaml
Deleting the file was moved to the next task.
> online course: Remove leftover instruction

- backend/cw_backend/model/task_solution_comments.py
- backend/cw_backend/model/task_solutions.py
- backend/cw_backend/views/tasks.py
- frontend/components/TaskReviewLessonSummary.js
Tato úprava přidá informaci o celkovém počtu odevzdaných verzí a celkovém počtu komentářů pro každý odevzdaný úkol do přehledové tabulky. Užitečné je to zejména pro přípravu na následující hodinu, při které se hodí vědět, se kterým úkolem měly účastnice nejvetší trable, byl nejvíce diskutovaný a musel se nejčastěji opravovat.
Nejsem expert na codebase tohodle projektu a na JS už vůbec ne, ale funguje to. Počet řešení jen využívá existující informace z API, počet komentářů jsem musel dodělat. Napadlo mě to udělat i jako samostatnou metodu pro `TaskSolution` a tu pak volat z metody `export`, ale to by znamenalo samostatný dotaz do db pro každé řešení a tak jsem to raději udělal mimo tu třídu do view a dotaz je tam jen jeden.
Prosím o review.
Fixes: …
> Add info about number of versions/comments to overview table
